version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord_eas_app
    restart: always
    env_file:
      - config/environment.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
